article:
  author: thomas
  content_type: article
  tags:
    - Kubernetes
    - Security
    - Operations
  permalinks:
    - kubernetes-certs-expired
  uuid: ac5e61c0-3c20-11ed-874d-a937075e186a
  active_dt: 1664034654731
info:
  title: Renewing Kubernetes certificates after they have expired
  abstract:
    format: text/plain
    text: >
      You opened your terminal one day, tried to check your pod status like you
      do every other day, and suddenly you can't. This article will help you
      rescue your Kubernetes cluster.
  article:
    format: text/markdown
    file: kubernetes-certs-expired.md
  name: kubernetes-certs-expired
