article:
  author: thomas
  content_type: article
  tags:
    - IBM API Connect
    - NTP
  permalinks:
    - ntp-on-api-connect
  uuid: 59c70a20-1673-11ed-874d-a937075e186a
  active_dt: 1659892020283
info:
  title: NTP on API Connect
  abstract:
    format: text/markdown
    text: When setting up API Connect on OVA, it's common to forget to configure
      NTP, but this is absolutely critical to keep your API Connect servers
      stable.
  article:
    format: text/markdown
    file: ntp-on-api-connect.md
  name: ntp-on-api-connect
