---
article:
  author: thomas
  content_type: article
  tags:
    - IBM API Connect
    - IBM DataPower Gateway
  permalinks:
    - v5c-to-api-gateway
  uuid: 5a0d3ae0-1673-11ed-874d-a937075e186a
  active_dt: 1659892020672
info:
  title: Moving APIs from the v5c to API Gateway
  abstract:
    format: text/plain
    text: The API Gateway performs 5-10&times; faster than the Version 5
      Compatibility Mode, but converting APIs to the API gateway requires
      planning.
  article:
    format: text/markdown
    file: v5c-to-api-gateway.md
  name: v5c-to-api-gateway
