---
article:
  author: thomas
  content_type: rocket
  tags:
    - JavaScript
info:
  title: >
    JavaScript's == equality operator's type conversion feature can have "interesting" implications:
  abstract:
    # Feature needed: markdown in rockets
    format: text/markdown
    text: >
      `[1,2] == [1,2]` is `false` but `[1,2] == "1,2"` is `true`
  name: array-equality
