---
article:
  author: thomas
  content_type: rocket
  tags:
    - JavaScript
info:
  title: >
    Safari doesn’t support regular expressions with zero-width lookbehind assertions
  abstract:
    format: text/plain
    text: >
      Chromium browers support them, but Safari will throw an exception if it encounters one.
  name: safari-regex
