article:
 author: thomas
 content_type: article
 tags:
 - cheat-notes
 - scripting
 - Linux
 permalinks:
 - extended-globbing

info:
 title: "Cheat notes: extended globbing"
 abstract:
  format: text/plain
  text: Using extended globbing to match more patterns in your shell scripts.
 article:
  format: text/markdown
  file: extended-globbing.md

