---
article:
  author: thomas
  # active_dt: <date to activate -- use this to queue articles>
  content_type: cheat
  tags:
    - cheat-notes
    - scripting
    - Linux
  permalinks:
    - test-commands

info:
  title: "Test commands"
  abstract:
    format: text/plain
    text: This is a list of test commands to use for shell scripts
  article:
    format: text/markdown
    file: test-commands.md
