article:
  author: thomas
  # active_dt: <date to activate -- use this to queue articles>
  content_type: cheat
  tags:
  - cheat-notes
  - scripting
  - Linux
  permalinks:
  - test-commands

info:
  title: "Test commands"
  abstract:
    format: text/plain
    text: 
  article:
    format: text/markdown
    file: test-commands.md
