---
article:
  author: thomas
  content_type: article
  tags:
    - IBM API Connect
    - IBM DataPower Gateway
    - Operations
    - High Availability
  permalinks:
    - removing-a-gateway-peer
  uuid: 59f8a170-1673-11ed-874d-a937075e186a
  active_dt: 1659892020566
info:
  title: Removing a gateway peer from a peer group
  abstract:
    format: text/plain
    text: When decommissioning and permanently removing a gateway from a peer
      group, it's a good idea to ensure the peer group knows it's gone.
      Otherwise, it may assume it's a regular outage and count the
      decommissioned gateway against quorum.
  article:
    format: text/markdown
    file: removing-a-gateway-peer.md
  name: removing-a-gateway-peer
