---
article:
  author: thomas
  content_type: cheat
  tags:
    - Scripting
    - Linux
  permalinks:
    - extended-globbing

info:
  title: "Extended Globbing"
  abstract:
    format: text/plain
    text: Using extended globbing to match more patterns in your shell scripts.
  article:
    format: text/markdown
    file: extended-globbing.md
