---
article:
  author: thomas
  content_type: article
  tags:
    - IBM API Connect
    - Operations
    - High Availability
    - Usability
  permalinks:
    - every-api-connect
  active_dt: 1664034654621
info:
  title: Things every API Connect installation should have
  abstract:
    format: text/plain
    text: >
      Make an API Connect installation more stable, more usable, and more
      professional.
  article:
    format: text/markdown
    file: every-api-connect.md
  name: every-api-connect
