---
article:
  author: thomas
  content_type: cheat
  tags:
    - JavaScript
    - Kubernetes
    - Vue.js
  permalinks:
    - deep-linking-vue

info:
  title: "Deep linking in Vue.js apps in Kubernetes"
  abstract:
    format: text/plain
    text: Using extended globbing to match more patterns in your shell scripts.
  article:
    format: text/markdown
    file: deep-linking-vue.md
